bookstore/config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'books/new'
  get 'books/create'
  get 'books/update'
  get 'books/edit'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'about/index'
  get 'about' => 'about#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :books
  resources :authors
  resources :categories
  resources :publishers
end

bookstore/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore/app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
end

bookstore/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
end

bookstore/app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true,
            length: {minimum: 3}
end

bookstore/app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

bookstore/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

bookstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookstore/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add new Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author Created"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    flash[:notice] = "Author Updated"
    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:notice] = "Author Removed"
    redirect_to authors_path
  end

  def index
    @authors = Author.all
  end

  private
  def author_params
    params.require(:author).permit(:first_name,:last_name)
  end
end

bookstore/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add new Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book Created"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    flash[:notice] = "Book Updated"
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book Removed"
    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
  def book_params
  params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :coverpath, :isbn, :price, :buy, :format,:excerpt, :pages,:year)
  end
end

bookstore/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add new Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:notice] = "Category Updated"
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category Removed"
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end
  private
  def category_params
    params.require(:category).permit(:name)
  end
end

bookstore/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add new Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created"
      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])
    @publisher.update(publisher_params)
    flash[:notice] = "Publisher Updated"
    redirect_to publishers_path
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:notice] = "Publisher Removed"
    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
  end

  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

bookstore/app/helpers/about_helper.rb
module AboutHelper
end

bookstore/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookstore/app/helpers/books_helper.rb
module BooksHelper
end

bookstore/app/helpers/categories_helper.rb
module CategoriesHelper
end

bookstore/app/helpers/publishers_helper.rb
module PublishersHelper
end

bookstore/app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Core Features
  Filters
  Templates (scoring models)
  Requirement rules (Skills, Seniority, Degree, Geolocation, Tags)
  Geolocation rules (address, education, experience)
  Notifications
  Profiles
  Bulk export
  Bulk import
  Reports & Analytics
  Sourcing monitoring
  Screening performance
  Competency mapping (internal insights)
  Market landscape (external insights)
  API access
  Maximum queries per second
  Processing time
  Security & account access
  Secure environment - HTTPS, API keys
  Multi-user access
</p>

bookstore/app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

bookstore/app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

bookstore/app/views/authors/edit.html.erb
<h2>Edit Authors</h2>

<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", authors_path, class: "btn btn-default" %>
<% end %>

bookstore/app/views/authors/index.html.erb
<h1> Authors </h1>

<table class="table table-striped">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Actions</th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name %></td>
      <td><%= author.last_name %></td>
      <td><%= link_to 'Edit', edit_author_path(author.id) %> | <%= link_to 'Delete', author_path(author), method: :delete, date: {confirm: 'Are you Sure'} %></td>
    </tr>
  <% end %>
</table>

bookstore/app/views/authors/new.html.erb
<h2>Add New Authors</h2>

<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <% @author.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", authors_path, class: "btn btn-default" %>
<% end %>

bookstore/app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

bookstore/app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

bookstore/app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

bookstore/app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

bookstore/app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :isbn %><br/>
    <%= f.text_field :isbn, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :category %><br/>
    <%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %><br/><br/>
  </div>
  <div class="form-group">
    <%= f.label :author %><br/>
    <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name,x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %><br/><br/>
  </div>
  <div class="form-group">
    <%= f.label :publisher %><br/>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name,x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %><br/><br/>
  </div>
  <div class="form-group">
    <%= f.label :format %><br/>
    <%= f.text_field :format, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :excerpt %><br/>
    <%= f.text_field :excerpt, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :pages %><br/>
    <%= f.number_field :pages, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :year %><br/>
    <%= f.text_field :year, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :coverpath %><br/>
    <%= f.text_field :coverpath, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :price %><br/>
    <%= f.text_field :price, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :buy %><br/>
    <%= f.text_field :buy, class:'form-control' %><br/>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", books_path, class: "btn btn-default" %>
<%end%>

bookstore/app/views/books/index.html.erb
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <%book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h3><%= book.title %></h3>
          <%= image_tag(book.coverpath) %>
          <%#= image_tag('Covers/1.jpg') %>
          <%= link_to 'Read More', book_path(book), class:'btn btn-primary' %>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

bookstore/app/views/books/new.html.erb
<h1>Add New Book</h1>

<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <% @book.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :isbn %><br/>
    <%= f.text_field :isbn, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :category %><br/>
    <%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %><br/><br/>
  </div>
  <div class="form-group">
    <%= f.label :author %><br/>
    <%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name,x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %><br/><br/>
  </div>
  <div class="form-group">
    <%= f.label :publisher %><br/>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name,x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %><br/><br/>
  </div>
  <div class="form-group">
    <%= f.label :format %><br/>
    <%= f.text_field :format, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :excerpt %><br/>
    <%= f.text_field :excerpt, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :pages %><br/>
    <%= f.number_field :pages, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :year %><br/>
    <%= f.text_field :year, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :coverpath %><br/>
    <%= f.text_field :coverpath, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :price %><br/>
    <%= f.text_field :price, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :buy %><br/>
    <%= f.text_field :buy, class:'form-control' %><br/>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", books_path, class: "btn btn-default" %>
<%end%>

bookstore/app/views/books/show.html.erb
<div id="books-show">
  <h2><%= @book.title %></h2>
  <div class="books-show-left">
    <%= image_tag(@book.coverpath) %>
  </div>
  <div class="books-show-right">
    <h1>Books Info</h1>
    <ul>
      <li><storng>Category:</storng><%= @book.category.name %></li>
      <li><storng>Author:</storng><%= @book.author.first_name %><%= @book.author.last_name %></li>
      <li><storng>Publisher:</storng><%= @book.publisher.name %></li>
      <li><storng>Year:</storng><%= @book.year %></li>
      <li><storng>ISBN:</storng><%= @book.isbn %></li>
      <li><storng>Format:</storng><%= @book.format %></li>
      <li><storng>Pages:</storng><%= @book.pages %></li>
    </ul>
    <%=link_to "Buy For " + @book.price, @book.buy, class:"btn btn-success",target:"_blank" %>
  </div>
  <div class="clearfix">
    <h1>Excerpt</h1>
    <p><%= @book.excerpt %></p>
  </div>

  <div> Admin Functions </div>
  <%= link_to 'Edit', edit_book_path(@book.id) %> | <%= link_to 'Delete', book_path(@book) , method: :delete, data: { confim: 'Are you Sure'} %>
</div>

bookstore/app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

bookstore/app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

bookstore/app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

bookstore/app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
  <!--  Check for errors-->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", categories_path, class: "btn btn-default" %>
<% end %>

bookstore/app/views/categories/index.html.erb
<h1> Categories </h1>

<table class="table table-striped">
  <tr>
    <th>Category Name</th>
    <th>Actions</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Edit', edit_category_path(category.id) %> | <%= link_to 'Delete', category_path(category), method: :delete, date: {confirm: 'Are you Sure'} %></td>
    </tr>
  <% end %>
</table>

bookstore/app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
<!--  Check for errors-->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      <%end%>
    <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", categories_path, class: "btn btn-default" %>
<% end %>

bookstore/app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div id="books-index">
  <% @books.each_slice(4) do |book| %>
    <div class="row">
      <%book.each do |book| %>
        <div class="col-md-3 col-sm-3">
          <h3><%= book.title %></h3>
          <%= image_tag(book.coverpath) %>
          <%#= image_tag('Covers/1.jpg') %>
          <%= link_to 'Read More', book_path(book), class:'btn btn-primary' %>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

bookstore/app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

bookstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title><%= @page_title ? @page_title : 'Welcome' %> | The BookStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
<!--          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
          <a class="<%= params[:controller] == 'books' ? 'active' : ''%>"><%= link_to 'Home', root_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">    <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="<%= params[:controller] == 'books' ? 'about' : ''%>"><%= link_to 'About', about_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">    <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'New Book', new_book_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">    <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'Authors', new_author_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">    <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'Categories', new_category_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">    <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'Publishers', new_publisher_path%></a>
        </li>

        <a class="nav-link" href="#"><%= link_to 'Manage Category', categories_path%></a>
        <a class="nav-link" href="#"><%= link_to 'Manage Author', authors_path%></a>
        <a class="nav-link" href="#"><%= link_to 'Manage Publishers', publishers_path%></a>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <header>
    <div class="container">
      <h1>The Bookstore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
    </div>
  </header>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <% if flash[:notice]%>
          <div class="alert alert-success"><%= flash[:notice] %></div>
          <%end %>
          <% if flash[:alert]%>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <%end %>
        <%= yield %>
        </div>
        <div class="col-md-4">
          <%= render 'partials/sidebar' %>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <p>Copyright &copy; 2020, All rights not Reserved</p>
    </div>
  </footer>
  </body>
</html>
 

bookstore/app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
<div class = "well">
  <h3>Location info</h3>
  <ul>
    <li>The Bookstore</li>
    <li>Lahore pakistan street 13</li>
    <li>Boston Dynamics 1992</li>
    <li>Phone Number (92)0312-3123213</li>
    <li>Email: practiceruby@gmail.com</li>
  </ul>
</div>
<%end%>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">
    <% @categories.each do |category| %>
      <%= link_to category.name, category_path(category.id), class:"list-group-item" %>
    <%end%>
</div>
<%end%>

bookstore/app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

bookstore/app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

bookstore/app/views/publishers/edit.html.erb
<h2>Edit Publishers</h2>

<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", publishers_path, class: "btn btn-default" %>
<% end %>

bookstore/app/views/publishers/index.html.erb
<h1> Publishers </h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  <% @publishers.each do |publisher| %>
    <tr>
      <td><%= publisher.name %></td>
      <td><%= link_to 'Edit', edit_publisher_path(publisher.id) %> | <%= link_to 'Delete', publisher_path(publisher), method: :delete, date: {confirm: 'Are you Sure'} %></td>
    </tr>
  <% end %>
</table>

bookstore/app/views/publishers/new.html.erb
<h2>Add New Publishers</h2>

<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <% @publisher.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <%end%>
  <%end%>
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class:'form-control' %><br/>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%=link_to "Cancel", publishers_path, class: "btn btn-default" %>
<% end %>

bookstore/app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

bookstore/app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>